# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jLfxM7geE-iiwB9owf1EwT0SoESgOche
"""



# -*- coding: utf-8 -*-
"""
Created on Sun Sep 27 10:36:20 2020

@author: ramak
"""



from apriori import apriori

from eclat import eclat

from fpGrowth import fp

import matplotlib.pyplot as plt

import os

import time 

from memory_profiler import memory_usage

Datasets = os.listdir('data')


times = []

import numpy as np
import matplotlib.pyplot as plt

support = 0.2
times = []
categorical = False

for file in Datasets:
    t = []
    if file == 'groceries.csv':
      categorical = True
    else:
         categorical = False
    print("running on dataset", file)
    file = 'data/'+file
  
    
    print("apriori")
    
    t.append(max(memory_usage((apriori,(file,0.15,categorical)))))
    
   
    
    print("eclat")
    
    t.append(max(memory_usage((eclat,(file,0.15,categorical)))))
    
    
    print("fp")
    
    t.append(max(memory_usage((fp,(file,0.15,categorical)))))
    
    
    times.append(t)

def cate_plot(data, labels):
    X = np.arange(len(data[0]))
    fig = plt.figure()
    ax = fig.add_axes([0,0,1,1])
    ax.bar(X + 0.00, data[0], color = 'b', width = 0.25)
    ax.bar(X + 0.25, data[1], color = 'g', width = 0.25)
    ax.bar(X + 0.50, data[2], color = 'r', width = 0.25)
    ax.set_ylabel('log10(time)')
    ax.set_title('Time taken by algirithm on various datasets')
    ax.set_xticks(X)
    ax.set_xticklabels(labels, rotation = 45)
    ax.legend(labels=['apriori', 'eclat', 'fp'])

import numpy as np
import math




X = Datasets

print(times)
t = np.array(times).T.tolist()
print(t)

cate_plot(t, Datasets)
plt.savefig('time_dataset'+str(support)+".png",bbox_inches='tight')
plt.show()